name: Default Bash
on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
        fail-fast: false
    steps:
    - uses: actions/checkout@v1

    - name: Default bash
      run: ./exit.sh

    - name: Shell bash
      run: ./exit.sh
      shell: bash
